export const articles = {
  "technisches-datenblatt-importfahrzeug": {
    de: { title: "Technisches Datenblatt für Importfahrzeuge", description: "Welche Fahrzeugdaten für Zulassung und Einzelprüfung relevant sein können und wie ein technisches Datenblatt vorbereitet wird.", intro: "Bei importierten Fahrzeugen reichen ausländische Zulassungsunterlagen für deutsche Verfahren nicht immer aus. Ein strukturiertes Datenblatt bündelt die verfügbaren technischen Angaben in nachvollziehbarer Form.", sections: [["Wozu dient das Datenblatt?", "Es kann technische Angaben wie Fahrzeugabmessungen, Massen, Leistung, Emissionswerte, Bereifung oder Typinformationen strukturiert zusammenführen. Welche Nachweise eine Behörde oder Prüfstelle im Einzelfall akzeptiert, entscheidet ausschließlich die zuständige Stelle."], ["Welche Unterlagen helfen?", "Ausländische Zulassungsdokumente, ein vorhandenes COC, Typenschilder, die eingeschlagene FIN und gut lesbare Fahrzeugfotos verbessern die eindeutige Zuordnung. Alle Daten sollten widerspruchsfrei demselben Fahrzeug zugeordnet werden können."], ["Was ist ausdrücklich nicht enthalten?", "Ein privat erstelltes Datenblatt ist weder eine Betriebserlaubnis noch ein Hersteller-COC und ersetzt keine amtliche oder sachverständige Entscheidung. Unser Service gibt deshalb keine Zulassungsgarantie."]]},
    en: { title: "Technical data sheets for imported vehicles", description: "What a structured technical data sheet can contribute when importing a vehicle.", intro: "Foreign registration documents do not always contain every item requested in German procedures. A structured data sheet consolidates the technical information that can be established.", sections: [["What is it used for?", "It can consolidate dimensions, masses, power, emissions, tyres and type information. The competent authority or inspection body decides which evidence is acceptable in each case."], ["Which documents help?", "Foreign registration papers, any available COC, type plates, the stamped VIN and clear vehicle photographs help establish an unambiguous match."], ["What is not included?", "A privately prepared data sheet is not an operating permit or manufacturer COC and cannot replace an official or expert decision. No registration outcome is guaranteed."]]},
  },
  "coc-papiere": {
    de: { title: "COC-Papiere: Original, Ersatz und Datenrecherche", description: "Was ein Certificate of Conformity ist und wie sich Hersteller-COC und Typdatenrecherche unterscheiden.", intro: "Das Certificate of Conformity bestätigt bei typgenehmigten Fahrzeugen die Übereinstimmung mit einem genehmigten Typ. Entscheidend ist, wer das Dokument ausstellt.", sections: [["Das Hersteller-COC", "Ein echtes COC wird vom Fahrzeughersteller oder einer dazu autorisierten Stelle für ein konkretes Fahrzeug ausgestellt. Es enthält typgenehmigungsbezogene Daten und darf nicht durch ein ähnlich gestaltetes Privatdokument ersetzt werden."], ["Wenn das Original fehlt", "Je nach Fahrzeug kann beim Hersteller ein Ersatz angefragt werden. Bei älteren, nicht-europäischen oder abweichenden Fahrzeugen kann stattdessen eine technische Prüfung mit ergänzender Datenrecherche erforderlich sein."], ["Unsere Leistung", "Wir prüfen eingereichte Unterlagen, recherchieren verfügbare Typdaten und dokumentieren das Ergebnis. Wir stellen kein Hersteller-COC aus und verwenden keine Gestaltung, die diesen Eindruck erweckt."]]},
    en: { title: "COC papers: originals, replacements and research", description: "The difference between a manufacturer COC and technical data research.", intro: "A Certificate of Conformity confirms that a type-approved vehicle conforms to its approved type. The issuer is decisive.", sections: [["Manufacturer COC", "A genuine COC is issued for a specific vehicle by the manufacturer or an authorised body. A privately produced look-alike cannot replace it."], ["If the original is missing", "A replacement may be available from the manufacturer. Older or non-European vehicles may instead require an inspection supported by additional data research."], ["Our service", "We review submitted documents, research available type data and document the result. We do not issue a manufacturer COC."]]},
  },
  "fin-fahrgestellnummer": {
    de: { title: "FIN richtig finden und fotografieren", description: "So unterscheidest du eingeschlagene FIN, Typenschild und Scheibenanzeige und vermeidest unleserliche Nachweise.", intro: "Die Fahrzeug-Identifizierungsnummer (FIN/VIN) besteht bei modernen Fahrzeugen regelmäßig aus 17 Zeichen. Für eine belastbare Zuordnung ist die direkt in die Karosserie oder den Rahmen eingeschlagene Nummer besonders wichtig.", sections: [["Wo befindet sich die FIN?", "Häufige Fundstellen sind Motorraum, Federbeindom, Bodenblech, Sitzbereich oder Fahrzeugrahmen. Die Position unterscheidet sich je nach Hersteller und Modell. Typenschild und Anzeige hinter der Windschutzscheibe sind zusätzliche, aber nicht identische Nachweise."], ["So gelingt das Foto", "Fläche vorsichtig reinigen, gleichmäßig ausleuchten, parallel fotografieren und alle Zeichen einschließlich Anfang und Ende vollständig abbilden. Spiegelungen, harte Schatten und digitale Nachbearbeitung vermeiden."], ["Plausibilität prüfen", "Die Zeichen I, O und Q werden in standardisierten 17-stelligen FIN nicht verwendet. Vergleiche die Nummer mit Zulassungsdokument und Typenschild. Bei Abweichungen sollte keine eigenständige Korrektur vorgenommen, sondern fachlicher Rat eingeholt werden."]]},
    en: { title: "How to find and photograph a VIN", description: "Distinguish the stamped VIN from labels and dashboard displays and create legible evidence.", intro: "Modern vehicle identification numbers generally contain 17 characters. The number stamped directly into the body or frame is particularly useful for reliable attribution.", sections: [["Where is it located?", "Common locations include the engine bay, strut tower, floor, seat area or frame. The position varies by make and model."], ["Taking a clear photo", "Clean the surface carefully, use even light, photograph it straight on and include every character. Avoid glare, hard shadows and digital editing."], ["Plausibility checks", "The letters I, O and Q are not used in standard 17-character VINs. Compare the number with registration documents and the type plate; seek professional advice if they differ."]]},
  },
} as const;

export type ArticleSlug = keyof typeof articles;

