import Link from "next/link";
import type { Locale } from "@/lib/i18n";
import { SITE } from "@/lib/site";

export const legalTitles = {
  impressum: "Impressum",
  datenschutz: "Datenschutzerklärung",
  agb: "Allgemeine Geschäftsbedingungen",
  widerruf: "Widerrufsbelehrung",
} as const;
export type LegalSlug = keyof typeof legalTitles;
type Section = { title: string; body: React.ReactNode };

function CompanyBlock() {
  return <>
    <p><strong>{SITE.operator}</strong><br/>Marienborner Straße 49<br/>55128 Mainz<br/>Deutschland</p>
    <p>Telefon: <a href="tel:+496131934070">{SITE.phone}</a><br/>E-Mail: <a href={`mailto:${SITE.email}`}>{SITE.email}</a></p>
  </>;
}

function sectionsFor(slug: LegalSlug, locale: Locale): Section[] {
  if (slug === "impressum") return [
    { title: "Angaben gemäß § 5 DDG", body: <CompanyBlock/> },
    { title: "Vertretung", body: <><p>Geschäftsführer: Ibrahim Aslantaş</p><p>Inhaltlich verantwortlich gemäß § 18 Abs. 2 MStV: Ibrahim Aslantaş, Anschrift wie oben.</p></> },
    { title: "Register und Umsatzsteuer", body: <p>Registergericht: Amtsgericht Mainz<br/>Handelsregister: HRB 52148<br/>Umsatzsteuer-Identifikationsnummer gemäß § 27a UStG: DE363417359</p> },
    { title: "Zuständige Stellen", body: <p>Industrie- und Handelskammer für Rheinhessen, Schillerplatz 7, 55116 Mainz.<br/>Handwerkskammer Rheinhessen, Dagobertstraße 2, 55116 Mainz.</p> },
    { title: "Verbraucherstreitbeilegung", body: <><p>Wir sind nicht bereit und nicht verpflichtet, an Streitbeilegungsverfahren vor einer Verbraucherschlichtungsstelle teilzunehmen.</p><p>Die frühere europäische Plattform zur Online-Streitbeilegung wurde zum 20. Juli 2025 eingestellt; deshalb wird kein veralteter OS-Link angegeben.</p></> },
    { title: "Haftung für Inhalte und Links", body: <p>Wir sind für eigene Inhalte nach den allgemeinen Gesetzen verantwortlich. Eine Verpflichtung zur Überwachung übermittelter oder gespeicherter fremder Informationen besteht nur im Rahmen der gesetzlichen Vorschriften. Verlinkte externe Inhalte liegen außerhalb unseres Einflussbereichs. Bei Bekanntwerden konkreter Rechtsverletzungen entfernen wir entsprechende Links unverzüglich.</p> },
    { title: "Urheberrecht", body: <p>Die von uns erstellten Inhalte und Werke unterliegen dem deutschen Urheberrecht. Jede Verwertung außerhalb der gesetzlichen Schranken bedarf der vorherigen Zustimmung des jeweiligen Rechteinhabers.</p> },
  ];

  if (slug === "datenschutz") return [
    { title: "1. Verantwortlicher", body: <><CompanyBlock/><p>Verantwortlicher im Sinne der Datenschutz-Grundverordnung (DSGVO) ist die oben genannte Gesellschaft, vertreten durch ihren Geschäftsführer Ibrahim Aslantaş.</p></> },
    { title: "2. Überblick über die Verarbeitung", body: <p>Wir verarbeiten Daten, die für die sichere Bereitstellung der Website, die Entgegennahme und Bearbeitung von Aufträgen, die Zahlungsabwicklung und die geschützte Bereitstellung von Ergebnisdokumenten erforderlich sind. Wir setzen keine Werbe-, Profiling- oder Reichweitenanalyse-Cookies ein.</p> },
    { title: "3. Aufruf der Website und Serverprotokolle", body: <p>Beim Aufruf werden technisch notwendige Verbindungsdaten verarbeitet, insbesondere IP-Adresse, Zeitpunkt, URL, HTTP-Status, Datenmenge, Referrer sowie Browser- und Geräteinformationen. Zweck sind Auslieferung, Stabilität, Fehleranalyse und Missbrauchsabwehr. Rechtsgrundlage ist Art. 6 Abs. 1 lit. f DSGVO. Das berechtigte Interesse liegt im sicheren Betrieb. Protokolldaten werden regelmäßig höchstens 30 Tage aufbewahrt, sofern kein Sicherheitsereignis eine längere Aufbewahrung erfordert.</p> },
    { title: "4. Hosting, Datenbank und Objektspeicher", body: <p>Die Anwendung, PostgreSQL-Datenbank und private Dokumentenablage werden über Railway Corporation, 548 Market St PMB 68956, San Francisco, CA 94104, USA, betrieben. Als Betriebsregion ist Europa (Amsterdam, Niederlande) vorgesehen. Railway verarbeitet Daten auf Grundlage eines Auftragsverarbeitungsvertrags. Da Railway ein US-Unternehmen ist und Teile des Betriebs aus den USA erfolgen können, sind Drittlandübermittlungen möglich. Als Garantien dienen insbesondere das EU-US Data Privacy Framework und, soweit erforderlich, EU-Standardvertragsklauseln. Informationen: <a href="https://railway.com/legal/privacy" rel="external">Railway Privacy Policy</a> und <a href="https://railway.com/legal/dpa" rel="external">Data Processing Addendum</a>.</p> },
    { title: "5. Auftrag und Fahrzeugunterlagen", body: <><p>Beim Auftrag verarbeiten wir Name, E-Mail, optional Telefon und Unternehmen, FIN, Hersteller, Modell, Erstzulassung, Herkunftsland, FIN-Fundstelle, freiwillige Hinweise sowie hochgeladene Zulassungs- und Fahrzeugdokumente. Außerdem speichern wir Zeitpunkt und Fassung der vertraglichen Erklärungen. Rechtsgrundlage ist Art. 6 Abs. 1 lit. b DSGVO. Angaben Dritter in Dokumenten verarbeiten wir, soweit erforderlich, zusätzlich auf Grundlage des berechtigten Interesses an einer eindeutigen Fahrzeugzuordnung, Art. 6 Abs. 1 lit. f DSGVO.</p><p>Ohne Pflichtangaben und -nachweise ist keine Bearbeitung möglich. Nicht erforderliche Informationen sollten geschwärzt werden, soweit die Nachweisfunktion erhalten bleibt.</p></> },
    { title: "6. Zahlungsabwicklung", body: <p>Bei aktivierter Onlinezahlung nutzen wir Stripe. Bestellreferenz, Betrag, Währung, E-Mail-Adresse und notwendige Zahlungsdaten werden an Stripe übermittelt. Karten- und Kontodaten werden direkt von Stripe erhoben und nicht in unserer Anwendung gespeichert. Rechtsgrundlage ist Art. 6 Abs. 1 lit. b DSGVO; Betrugsprävention kann auf Art. 6 Abs. 1 lit. f DSGVO beruhen. Je nach Konstellation handeln Stripe Payments Europe, Limited und weitere Stripe-Unternehmen als Verantwortliche oder Auftragsverarbeiter. Informationen: <a href="https://stripe.com/de/privacy" rel="external">Stripe Datenschutzerklärung</a>. Ist Stripe nicht aktiviert, erfolgt die Zahlungsabstimmung individuell.</p> },
    { title: "7. Geschützter Status und Backoffice", body: <p>Der persönliche Auftragsstatus nutzt einen zufällig erzeugten geheimen Zugriffscode, der nur als Hash gespeichert wird. Das interne Backoffice setzt nach Anmeldung ein technisch notwendiges, HTTP-only geschütztes Sitzungscookie (<code>td_admin</code>) mit höchstens acht Stunden Laufzeit. Rechtsgrundlage ist Art. 6 Abs. 1 lit. f DSGVO; das Interesse liegt in Zugriffsschutz und sicherer Auftragsbearbeitung. Einwilligungsbedürftige Cookies werden nicht eingesetzt.</p> },
    { title: "8. Empfänger", body: <p>Zugriff erhalten nur befugte Beschäftigte und Dienstleister, soweit dies für Auftragsbearbeitung, Hosting, Zahlung oder gesetzliche Pflichten erforderlich ist. Ein Verkauf oder eine Weitergabe zu Werbung findet nicht statt. Behörden, Gerichte oder Prüfstellen erhalten Daten nur bei gesetzlicher Verpflichtung oder geeigneter Rechtsgrundlage.</p> },
    { title: "9. Speicherdauer", body: <p>Auftrags- und Abrechnungsdaten werden entsprechend handels- und steuerrechtlicher Pflichten regelmäßig sechs beziehungsweise zehn Jahre aufbewahrt. Fahrzeugunterlagen und Ergebnisdateien löschen wir grundsätzlich nach Ablauf angemessener Reklamations- und Nachweisfristen, regelmäßig spätestens 12 Monate nach Abschluss, soweit keine gesetzliche Pflicht, laufende Auseinandersetzung oder Vereinbarung entgegensteht. Nicht abgeschlossene Aufträge können nach 90 Tagen gelöscht werden. Sicherungskopien werden im üblichen Überschreibzyklus bereinigt.</p> },
    { title: "10. Rechtsgrundlagen und Einwilligungen", body: <p>Maßgeblich sind insbesondere Art. 6 Abs. 1 lit. b DSGVO (Vertrag), lit. c (rechtliche Pflicht) und lit. f (berechtigte Interessen). Soweit eine Einwilligung eingeholt wird, gilt lit. a. Sie kann jederzeit mit Wirkung für die Zukunft widerrufen werden; die Rechtmäßigkeit bis zum Widerruf bleibt unberührt.</p> },
    { title: "11. Rechte betroffener Personen", body: <p>Du hast im gesetzlichen Umfang Rechte auf Auskunft (Art. 15 DSGVO), Berichtigung (Art. 16), Löschung (Art. 17), Einschränkung (Art. 18), Datenübertragbarkeit (Art. 20) und Widerspruch (Art. 21). Kontakt: <a href={`mailto:${SITE.email}`}>{SITE.email}</a>. Außerdem besteht ein Beschwerderecht bei einer Datenschutzaufsichtsbehörde, insbesondere beim Landesbeauftragten für den Datenschutz und die Informationsfreiheit Rheinland-Pfalz, Hintere Bleiche 34, 55116 Mainz, <a href="https://www.datenschutz.rlp.de" rel="external">datenschutz.rlp.de</a>.</p> },
    { title: "12. Sicherheit und automatisierte Entscheidungen", body: <p>Die Übertragung ist TLS-verschlüsselt. Dokumente liegen nicht öffentlich zugänglich; Downloads erfolgen über kurzlebige Links. Statuslinks und Zugangsdaten sind vertraulich zu behandeln. Es findet keine ausschließlich automatisierte Entscheidung mit rechtlicher oder ähnlich erheblicher Wirkung und kein Profiling statt.</p> },
    { title: "13. Aktualisierung", body: <p>Wir passen diese Erklärung an, wenn sich Verarbeitung, Dienstleister oder Rechtslage ändern. Maßgeblich ist die veröffentlichte Fassung.</p> },
  ];

  if (slug === "agb") return [
    { title: "1. Geltungsbereich und Anbieter", body: <p>Diese AGB gelten für Verträge über den digitalen Fahrzeugdaten- und Dokumentenservice zwischen der {SITE.operator}, Marienborner Straße 49, 55128 Mainz („Anbieter“) und ihren Kundinnen und Kunden. Abweichende Bedingungen gelten nur bei ausdrücklicher Zustimmung in Textform.</p> },
    { title: "2. Leistungsgegenstand", body: <><p>Das Komplettpaket umfasst die Prüfung eingereichter Fahrzeugunterlagen, Recherche und strukturierte Aufbereitung verfügbarer Fahrzeug- und Typdaten, die Dokumentation der vom Auftraggeber am Fahrzeug geprüften FIN sowie ein COC-/Typdaten-Prüfergebnis. Umfang und Aussagekraft hängen von Fahrzeug, Datenlage und Unterlagenqualität ab.</p><p>Der Anbieter stellt <strong>kein Hersteller-COC</strong>, keine Betriebserlaubnis, kein amtliches Gutachten und keine Zulassung aus. Die Leistung ersetzt keine Behörden- oder Prüfstellenentscheidung. Ein bestimmtes Zulassungs-, Eintragungs- oder Anerkennungsergebnis wird nicht geschuldet.</p></> },
    { title: "3. Vertragsschluss", body: <><p>Die Darstellung ist ein verbindliches Angebot, soweit im Bestellprozess nichts anderes angegeben wird. Durch Absenden des verbindlich gekennzeichneten Auftrags nimmt der Kunde es an. Der Eingang wird elektronisch bestätigt. Bei erkennbaren technischen oder preislichen Fehlern kann der Anbieter unverzüglich anfechten; Zahlungen werden erstattet.</p><p>Vertragssprache ist Deutsch. Der Vertragstext ist nicht dauerhaft über ein Kundenkonto abrufbar; Bestellübersicht, Statuslink, AGB und Widerrufsbelehrung sollten gespeichert werden.</p></> },
    { title: "4. Mitwirkungspflichten", body: <><p>Der Kunde stellt richtige, vollständige und lesbare Angaben und Dateien bereit, prüft die eingeschlagene FIN unmittelbar am Fahrzeug und teilt deren Fundstelle wahrheitsgemäß mit. Er versichert, zur Übermittlung berechtigt zu sein und keine Rechte Dritter zu verletzen. Manipulierte, schädliche oder sachfremde Inhalte sind unzulässig.</p><p>Rückfragen sind angemessen zeitnah zu beantworten. Fehlende, unlesbare oder widersprüchliche Unterlagen verlängern Bearbeitungszeiten. Ungeeignete Dateien dürfen zurückgewiesen werden.</p></> },
    { title: "5. Preise und Zahlung", body: <p>Der Preis des Komplettpakets beträgt {SITE.price} einschließlich gesetzlicher Umsatzsteuer. Es gilt der angezeigte Preis. Die Zahlung erfolgt je nach Verfügbarkeit über Stripe oder einen individuell mitgeteilten Zahlungsweg. Die kostenpflichtige Bearbeitung beginnt grundsätzlich nach bestätigtem Zahlungseingang, soweit nichts anderes vereinbart wird.</p> },
    { title: "6. Bearbeitung und Bereitstellung", body: <><p>Genannte Zeiten sind Bearbeitungsziele, keine garantierten Fixtermine, sofern nicht ausdrücklich ein verbindlicher Termin bestätigt wurde. Ergebnisse werden im geschützten Statusbereich oder vereinbartem Weg bereitgestellt. Geheimen Statuslink und Zugriffscode muss der Kunde schützen und Dokumente zeitnah sichern.</p><p>Zumutanbare Teilleistungen sind zulässig. Ist keine belastbare Bearbeitung möglich, fordert der Anbieter Ergänzungen an. Bleibt die Leistung trotz angemessener Mitwirkung endgültig unmöglich, gelten die gesetzlichen Rücktritts- und Erstattungsregeln.</p></> },
    { title: "7. Rechte an Arbeitsergebnissen", body: <p>Nach vollständiger Zahlung erhält der Kunde ein einfaches Recht, die individuellen Ergebnisse für eigene Fahrzeug-, Zulassungs-, Prüf- und Nachweiszwecke zu verwenden und zuständigen Stellen zu übermitteln. Vorlagen, Software, Datenbanken und Methodik verbleiben beim Rechteinhaber. Irreführende Veränderung, Weiterverkauf als eigenes Produkt oder Darstellung als Hersteller-COC sind unzulässig.</p> },
    { title: "8. Mängelrechte", body: <p>Es gelten die gesetzlichen Mängelrechte. Maßgeblich ist der vereinbarte Umfang unter Berücksichtigung gelieferter und objektiv verfügbarer Informationen. Ein Mangel liegt nicht allein vor, weil eine Behörde zusätzliche Nachweise verlangt oder eine Zulassung ablehnt. Unstimmigkeiten sollten mit Referenz an <a href={`mailto:${SITE.email}`}>{SITE.email}</a> gemeldet werden.</p> },
    { title: "9. Haftung", body: <p>Der Anbieter haftet unbeschränkt bei Vorsatz und grober Fahrlässigkeit, bei Verletzung von Leben, Körper oder Gesundheit, nach dem Produkthaftungsgesetz und im Umfang übernommener Garantien. Bei leicht fahrlässiger Verletzung wesentlicher Vertragspflichten ist die Haftung auf den vorhersehbaren, typischen Schaden begrenzt. Im Übrigen ist die Haftung für leichte Fahrlässigkeit ausgeschlossen. Zwingende Verbraucherrechte bleiben unberührt.</p> },
    { title: "10. Widerrufsrecht für Verbraucher", body: <p>Es gilt die gesonderte <Link href={`/${locale}/widerruf`}>Widerrufsbelehrung</Link>. Wird ausdrücklich ein Beginn während der Widerrufsfrist verlangt, kann bei Widerruf Wertersatz für den erbrachten Anteil geschuldet sein. Das Recht erlischt bei vollständiger Erbringung, wenn der Verbraucher vorher ausdrücklich zugestimmt und den Verlust bei vollständiger Erfüllung bestätigt hat.</p> },
    { title: "11. Verbraucherstreitbeilegung", body: <p>Der Anbieter ist nicht bereit und nicht verpflichtet, an Streitbeilegungsverfahren vor einer Verbraucherschlichtungsstelle teilzunehmen. Die EU-Online-Streitbeilegungsplattform wurde zum 20. Juli 2025 eingestellt.</p> },
    { title: "12. Schlussbestimmungen", body: <p>Es gilt deutsches Recht unter Ausschluss des UN-Kaufrechts. Bei Verbrauchern gilt dies nur, soweit zwingender Schutz ihres gewöhnlichen Aufenthaltsstaats erhalten bleibt. Für Kaufleute und juristische Personen des öffentlichen Rechts ist Mainz ausschließlicher Gerichtsstand, soweit zulässig. Individuelle Abreden und zwingendes Recht gehen vor.</p> },
  ];

  return [
    { title: "Widerrufsrecht", body: <><p>Verbraucher haben das Recht, binnen vierzehn Tagen ohne Angabe von Gründen diesen Vertrag zu widerrufen. Die Frist beträgt vierzehn Tage ab dem Tag des Vertragsschlusses.</p><p>Um das Widerrufsrecht auszuüben, musst du uns mittels eindeutiger Erklärung, zum Beispiel Brief oder E-Mail, über deinen Entschluss informieren:</p><CompanyBlock/><p>Du kannst das unten stehende Muster verwenden; es ist nicht vorgeschrieben. Zur Fristwahrung reicht das rechtzeitige Absenden der Mitteilung.</p></> },
    { title: "Folgen des Widerrufs", body: <><p>Wenn du widerrufst, erstatten wir alle erhaltenen Zahlungen unverzüglich und spätestens binnen vierzehn Tagen ab Eingang des Widerrufs. Wir verwenden dasselbe Zahlungsmittel wie bei der ursprünglichen Transaktion, sofern nicht ausdrücklich etwas anderes vereinbart wurde; dafür werden keine Entgelte berechnet.</p><p>Hast du verlangt, dass die Dienstleistung während der Widerrufsfrist beginnt, musst du einen angemessenen Betrag für den bis zum Widerruf erbrachten Anteil zahlen.</p></> },
    { title: "Vorzeitiges Erlöschen", body: <p>Das Widerrufsrecht bei einer Dienstleistung erlischt, wenn wir vollständig geleistet haben und erst begonnen haben, nachdem du ausdrücklich dem Beginn vor Fristablauf zugestimmt und deine Kenntnis vom Verlust des Widerrufsrechts bei vollständiger Vertragserfüllung bestätigt hast.</p> },
    { title: "Muster-Widerrufsformular", body: <div className="withdrawal-form"><p>(Wenn du den Vertrag widerrufen willst, fülle dieses Formular aus und sende es zurück.)</p><p>An:<br/>{SITE.operator}<br/>Marienborner Straße 49<br/>55128 Mainz<br/>E-Mail: {SITE.email}</p><p>Hiermit widerrufe(n) ich/wir (*) den Vertrag über folgende Dienstleistung:</p><p>________________________________________</p><p>Bestellt am (*) / Referenz:</p><p>________________________________________</p><p>Name und Anschrift des/der Verbraucher(s):</p><p>________________________________________</p><p>Datum und Unterschrift (nur auf Papier):</p><p>________________________________________</p><p><small>(*) Unzutreffendes streichen.</small></p></div> },
  ];
}

export function LegalContent({ slug, locale }: { slug: LegalSlug; locale: Locale }) {
  return <>
    {locale === "en" && <div className="legal-notice"><strong>Language notice</strong><p>The legally authoritative information is provided in German because the operator and service are based in Germany. For English assistance, contact <a href={`mailto:${SITE.email}`}>{SITE.email}</a>.</p><Link href={`/de/${slug}`}>German canonical version</Link></div>}
    {sectionsFor(slug, locale).map((section) => <section key={section.title}><h2>{section.title}</h2>{section.body}</section>)}
  </>;
}

