import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { Icon } from "@/components/icons";
import { OrderForm } from "@/components/order-form";
import { SiteFooter } from "@/components/site-footer";
import { SiteHeader } from "@/components/site-header";
import { copy, isLocale, type Locale } from "@/lib/i18n";
import { PRODUCTS, SITE } from "@/lib/site";

export async function generateMetadata({ params }: { params: Promise<{ locale: string }> }): Promise<Metadata> {
  const { locale } = await params;
  const de = locale === "de";
  return {
    title: de ? "Technisches Datenblatt, Typgenehmigungsdaten & FIN-Bestätigung" : "Technical data sheet, type-approval data & VIN confirmation",
    description: de ? "Ein digitales Fahrzeugdatenpaket für 24,99 € inkl. MwSt.: COC-/Typgenehmigungsdaten, technisches Datenblatt und FIN-Bestätigung mit Akzeptanzgarantie." : "One digital vehicle-data package for €24.99 incl. VAT: COC/type-approval data, technical data sheet and VIN confirmation with acceptance guarantee.",
    keywords: de ? ["COC", "COC Papiere", "Datenblatt", "technisches Datenblatt", "Geld zurück Garantie Datenblatt", "Zulassung Europa", "ausländisches Fahrzeug in Deutschland zulassen", "deutsches Fahrzeug im EU-Ausland zulassen", "Importfahrzeug Zulassung", "FIN Bestätigung", "Typgenehmigungsdatenblatt"] : ["COC", "technical data sheet", "money-back guarantee", "register vehicle Europe", "register imported vehicle Germany", "vehicle registration EU", "VIN confirmation"],
    alternates: { canonical: `/${locale}`, languages: { "de-DE": "/de", "en": "/en" } },
  };
}

const faqDe = [
  ["Was bedeutet die Geld-zurück-Garantie?", "Lehnt eine zuständige Zulassungsstelle in Europa unser unverändertes technisches Datenblatt als technischen Nachweis für das beauftragte Fahrzeug ab, erstatten wir den vollständigen gezahlten Preis des betroffenen Auftrags. Dafür benötigen wir innerhalb von 90 Tagen nach Dokumentbereitstellung den schriftlichen Ablehnungsnachweis. Andere Zulassungshindernisse sind nicht umfasst."],
  ["Was ist im 24,99-€-Paket enthalten?", "Du erhältst ein COC-/Typgenehmigungsdatenblatt, ein technisches Datenblatt und eine FIN-Bestätigung als digitale Dokumente. Der einmalige Endpreis beträgt 24,99 € inklusive gesetzlicher Mehrwertsteuer."],
  ["Kann ich damit ein ausländisches Fahrzeug in Deutschland zulassen?", "Die Dokumente bereiten technische Fahrzeug- und Typdaten für das Zulassungsverfahren auf. Ob weitere Nachweise, eine HU/AU oder eine Einzelbegutachtung erforderlich sind und ob die Zulassung erteilt wird, entscheidet die zuständige Behörde beziehungsweise Prüfstelle im Einzelfall."],
  ["Unterstützt ihr deutsche Fahrzeuge bei der Zulassung im EU-Ausland?", "Ja. Wir strukturieren die technischen Fahrzeug- und Typdaten auch für die Vorlage im EU-Ausland. Da die Zulassungsregeln national unterschiedlich sind, sollte die konkrete Unterlagenliste vorher bei der zuständigen Behörde des Ziellands geprüft werden."],
  ["Erhalte ich ein Hersteller-COC?", "Nein. Ein echtes COC wird ausschließlich vom Fahrzeughersteller oder einer autorisierten Stelle ausgestellt. Unser COC-/Typgenehmigungsdatenblatt bereitet verfügbare Typdaten auf und ist als solches klar gekennzeichnet."],
  ["Welche Unterlagen werden benötigt?", "Wir benötigen ein vollständig lesbares Zulassungsdokument, ein Fahrzeugfoto und ein scharfes Foto der direkt am Fahrzeug eingeschlagenen FIN. Je besser die Unterlagen lesbar sind, desto eindeutiger lassen sich Fahrzeug und Typdaten zuordnen."],
  ["Führt ihr HU/AU oder die Zulassung durch?", "Nein. Das einzige angebotene Produkt ist das digitale Fahrzeugdatenpaket. HU/AU, Fahrzeugvorführung, Behördengänge und Zulassungsgebühren sind nicht Bestandteil des Angebots."],
  ["Sind meine Dokumente öffentlich?", "Nein. Uploads liegen in einem privaten Objektspeicher. Der Abruf erfolgt nur über geschützte und zeitlich begrenzte Links."],
];

const faqEn = [
  ["What does the money-back guarantee cover?", "If a competent registration authority in Europe rejects our unaltered technical data sheet as technical evidence for the commissioned vehicle, we refund the full price paid for that order. We need written evidence of the rejection within 90 days after delivery. Other obstacles to registration are not covered."],
  ["What does the €24.99 package include?", "You receive a COC/type-approval data sheet, a technical data sheet and a VIN confirmation as digital documents. The one-off total price is €24.99 including VAT."],
  ["Can the documents help register a foreign vehicle in Germany?", "The documents structure technical vehicle and type data for the registration process. The competent authority or inspection body decides whether further evidence, HU/AU or an individual inspection is required and whether registration can be granted."],
  ["Do you support German vehicles being registered elsewhere in the EU?", "Yes. We structure vehicle and type data for use in another EU country. Requirements differ by country, so the destination authority's document list should be checked first."],
  ["Will I receive a manufacturer COC?", "No. A genuine COC can only be issued by the manufacturer or an authorised body. Our COC/type-approval data sheet clearly identifies itself as a technical data compilation."],
  ["Which documents are required?", "We need a legible registration document, a vehicle photo and a clear photo of the VIN stamped into the vehicle. Clear records make the vehicle and type-data attribution more reliable."],
  ["Do you perform HU/AU or registration?", "No. The only product offered is the digital vehicle-data package. HU/AU, vehicle appointments, authority visits and registration fees are not part of the service."],
  ["Are my documents public?", "No. Uploads remain in private object storage and are accessed only through protected, short-lived links."],
];

const examples = [
  { slug: "coc-typgenehmigungsdatenblatt-muster", de: "COC-/\u200bTypgenehmigungsdatenblatt", en: "COC/type-approval data sheet", textDe: "Zweiseitiges Querformat nach dem tatsächlich verwendeten Typgenehmigungsdaten-Layout.", textEn: "Two-page landscape format based on the type-approval data layout actually used.", width: 1403, height: 993 },
  { slug: "technisches-datenblatt-muster", de: "Technisches Datenblatt", en: "Technical data sheet", textDe: "Zulassungsrelevante Fahrzeugdaten im Feldraster der Zulassungsbescheinigung Teil I.", textEn: "Registration-relevant vehicle data in the field grid of the German registration certificate Part I.", width: 993, height: 1403 },
  { slug: "fin-bestaetigung-muster", de: "FIN-Bestätigung", en: "VIN confirmation", textDe: "Formale Bestätigung der am Fahrzeug abgelesenen Fahrzeug-Identifizierungsnummer.", textEn: "Formal confirmation of the vehicle identification number read from the vehicle.", width: 993, height: 1403 },
] as const;

const exampleAssetVersion = "20260714-reference-v2";

export default async function Home({ params }: { params: Promise<{ locale: string }> }) {
  const { locale: rawLocale } = await params;
  if (!isLocale(rawLocale)) notFound();
  const locale: Locale = rawLocale;
  const t = copy[locale];
  const de = locale === "de";
  const faq = de ? faqDe : faqEn;
  const structuredData = {
    "@context": "https://schema.org", "@graph": [
      { "@type": "Organization", name: SITE.operator, url: "https://technisches-datenblatt.de", address: { "@type": "PostalAddress", streetAddress: "Marienborner Straße 49", postalCode: "55128", addressLocality: "Mainz", addressCountry: "DE" }, email: SITE.email, telephone: SITE.phone },
      { "@type": "Service", name: de ? "Technisches Datenblatt mit europaweiter Akzeptanzgarantie" : "Technical data sheet with Europe-wide acceptance guarantee", description: de ? "Wird das Datenblatt von der zuständigen Zulassungsstelle in Europa nicht als technischer Nachweis akzeptiert, wird der gezahlte Paketpreis nach den Garantiebedingungen erstattet." : "If the competent registration authority in Europe does not accept the data sheet as technical evidence, the package price paid is refunded under the guarantee terms.", provider: { "@type": "Organization", name: SITE.operator }, areaServed: "Europe", termsOfService: `https://technisches-datenblatt.de/${locale}/garantie`, offers: [
        { "@type": "Offer", name: PRODUCTS.data.name, price: "24.99", priceCurrency: "EUR", availability: "https://schema.org/InStock" },
      ] },
      { "@type": "FAQPage", mainEntity: faq.map(([name, text]) => ({ "@type": "Question", name, acceptedAnswer: { "@type": "Answer", text } })) },
    ],
  };

  return <>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData) }} />
    <SiteHeader locale={locale} />
    <main>
      <section className="hero" id="top">
        <div className="hero-copy"><span className="kicker"><i />{t.hero.kicker}</span><h1>{t.hero.titleA}<br/><em>{t.hero.titleB}</em></h1><p>{t.hero.text}</p><div className="button-row"><a className="button primary" href="#auftrag">{t.hero.primary}<Icon name="arrow" /></a><Link className="button ghost" href={`/${locale}/garantie`}>{de ? "Garantiebedingungen" : "Guarantee terms"}</Link></div><div className="trust"><span><Icon name="shield" size={17}/>{de ? "Europaweite Akzeptanzgarantie" : "Europe-wide acceptance guarantee"}</span><span><Icon name="check" size={17}/>{de ? "24,99 € inkl. MwSt." : "€24.99 incl. VAT"}</span><span><Icon name="check" size={17}/>{de ? "Drei digitale Dokumente" : "Three digital documents"}</span></div></div>
        <div className="hero-visual" aria-label={de ? "Vorschau eines technischen Datenblatts" : "Technical data sheet preview"}><div className="visual-top"><span>TD / VEHICLE DATA</span><span>01 — 03</span></div><div className="visual-vin"><small>VEHICLE IDENTIFICATION NUMBER</small><strong>WVW •••••••• 386752</strong></div><div className="visual-grid"><div><small>{de ? "Hersteller" : "Make"}</small><b>Volkswagen</b></div><div><small>{de ? "Baureihe" : "Series"}</small><b>Typ 1J</b></div><div><small>{de ? "Leistung" : "Power"}</small><b>110 kW</b></div><div><small>{de ? "Kraftstoff" : "Fuel"}</small><b>Diesel</b></div></div><div className="visual-seal"><Icon name="shield" size={25}/><span>{de ? "AKZEPTANZ GARANTIERT" : "ACCEPTANCE GUARANTEED"}</span></div></div>
      </section>

      <section className="route-band" aria-label={de ? "Zulassungsrichtungen" : "Registration directions"}><div><small>EU → DE</small><strong>{de ? "Ausländisches Fahrzeug in Deutschland zulassen" : "Register a foreign vehicle in Germany"}</strong></div><i>↔</i><div><small>DE → EU</small><strong>{de ? "Deutsches Fahrzeug im EU-Ausland zulassen" : "Register a German vehicle elsewhere in the EU"}</strong></div></section>

      <section className="marquee" aria-label={de ? "Leistungsübersicht" : "Service overview"}><div>{["TYPGENEHMIGUNGSDATEN", "TECHNISCHES DATENBLATT", "FIN-BESTÄTIGUNG", "TYPGENEHMIGUNGSDATEN", "TECHNISCHES DATENBLATT", "FIN-BESTÄTIGUNG"].map((item, i) => <span key={`${item}-${i}`}>{item}<i>↗</i></span>)}</div></section>

      <section className="section services" id="leistung"><div className="section-heading"><span className="kicker">01 / {de ? "Unterlagen" : "Documents"}</span><h2>{de ? "Technische Klarheit für die nächste Zulassungsstelle." : "Technical clarity for the next registration authority."}</h2><p>{de ? "Wir übersetzen verstreute Fahrzeugdaten in einen nachvollziehbaren Dokumentensatz – für Import nach Deutschland und Zulassung deutscher Fahrzeuge im EU-Ausland." : "We turn scattered vehicle data into a traceable document set for imports into Germany and German vehicles moving elsewhere in the EU."}</p></div><div className="service-grid">
        <article><span>01</span><Icon name="file" size={30}/><h3>{de ? "Technisches Datenblatt" : "Technical data sheet"}</h3><p>{de ? "Relevante Fahrzeug- und Typdaten werden übersichtlich und nachvollziehbar aufbereitet." : "Relevant vehicle and type data is presented in a structured, traceable format."}</p></article>
        <article><span>02</span><Icon name="shield" size={30}/><h3>{de ? "FIN-Bestätigung" : "VIN confirmation"}</h3><p>{de ? "Die von dir am Fahrzeug geprüfte, eingeschlagene FIN wird auftragsbezogen dokumentiert." : "The stamped VIN you checked on the vehicle is documented for the order."}</p></article>
        <article><span>03</span><Icon name="check" size={30}/><h3>{de ? "COC-/Typgenehmigungsdaten" : "COC/type-approval data"}</h3><p>{de ? "Verfügbare Typinformationen werden fachlich eingeordnet – klar getrennt von einem Hersteller-COC." : "Available type information is reviewed and clearly distinguished from a manufacturer-issued COC."}</p></article>
      </div></section>

      <section className="bundle-section guarantee-section"><div className="bundle-price guarantee-mark"><small>{de ? "Unser Versprechen" : "Our promise"}</small><strong>100<span>%</span></strong><p>{de ? "des Paketpreises zurück" : "of the package price back"}</p></div><div className="bundle-copy"><span className="kicker light">02 / {de ? "Unser USP" : "Our USP"}</span><h2>{de ? "Datenblatt akzeptiert. Oder Geld zurück." : "Data sheet accepted. Or your money back."}</h2><p>{de ? "Wir gewährleisten die Akzeptanz unseres technischen Datenblatts bei der zuständigen Zulassungsstelle innerhalb Europas. Wird es dort nicht als technischer Nachweis akzeptiert, erstatten wir den vollständigen Preis des betroffenen Auftrags." : "We guarantee acceptance of our technical data sheet by the competent registration authority within Europe. If it is not accepted there as technical evidence, we refund the full price of the affected order."}</p><ul><li><Icon name="shield"/> {de ? "Gültig bei zuständigen Zulassungsstellen in Europa" : "Valid with competent registration authorities in Europe"}</li><li><Icon name="check"/> {de ? "Vollständiger gezahlter Paketpreis zurück" : "Full package price paid refunded"}</li><li><Icon name="check"/> {de ? "Schriftlicher Ablehnungsnachweis innerhalb von 90 Tagen" : "Written proof of rejection within 90 days"}</li></ul><small>{de ? "Die Garantie betrifft die Akzeptanz unseres unveränderten Datenblatts. Andere Zulassungsvoraussetzungen, Fahrzeugmängel, Umbauten sowie fehlende Behörden-, Steuer-, Zoll- oder Versicherungsunterlagen bleiben unberührt." : "The guarantee covers acceptance of our unaltered data sheet. Other registration requirements, vehicle defects or modifications, and missing authority, tax, customs or insurance documents remain unaffected."}</small><Link className="guarantee-link" href={`/${locale}/garantie`}>{de ? "Vollständige Garantiebedingungen" : "Full guarantee terms"}<Icon name="arrow"/></Link></div></section>

      <section className="process" id="ablauf"><div className="process-intro"><span className="kicker light">03 / {de ? "Ablauf" : "Process"}</span><h2>{de ? "Vom Upload zu drei Dokumenten." : "From upload to three documents."}</h2><p>{de ? "Ein kompakter digitaler Ablauf ohne Paketwahl, Fahrzeugvorführung oder Behördengang." : "A compact digital process without package selection, vehicle appointment or authority visit."}</p></div><ol><li><b>01</b><div><h3>{de ? "Unterlagen hochladen" : "Upload documents"}</h3><p>{de ? "Zulassungsdokument, Fahrzeugansicht und eingeschlagene FIN sicher übermitteln." : "Securely submit the registration paper, vehicle view and stamped VIN."}</p></div></li><li><b>02</b><div><h3>{de ? "Fahrzeug zuordnen" : "Identify the vehicle"}</h3><p>{de ? "Wir prüfen FIN, Lesbarkeit und die eindeutige Zuordnung der Fahrzeugunterlagen." : "We review the VIN, legibility and unambiguous attribution of the vehicle records."}</p></div></li><li><b>03</b><div><h3>{de ? "Typdaten aufbereiten" : "Structure type data"}</h3><p>{de ? "Verfügbare Typgenehmigungs- und Fahrzeugdaten werden fachlich strukturiert." : "Available type-approval and vehicle data is structured professionally."}</p></div></li><li><b>04</b><div><h3>{de ? "Digital bereitstellen" : "Deliver digitally"}</h3><p>{de ? "Du erhältst Typgenehmigungsdatenblatt, technisches Datenblatt und FIN-Bestätigung im geschützten Statusbereich." : "You receive the type-approval data sheet, technical data sheet and VIN confirmation in the protected status area."}</p></div></li></ol></section>

      <section className="section examples" id="beispiele"><div className="section-heading"><span className="kicker">04 / {de ? "Beispiele" : "Examples"}</span><h2>{de ? "So sehen die Ergebnisdokumente aus." : "See what the result documents look like."}</h2><p>{de ? "Die Muster basieren auf den tatsächlich verwendeten Dokumentenformaten, enthalten ausschließlich fiktive Daten und sind nicht zur Vorlage bei Behörden oder Prüfstellen bestimmt." : "The examples are based on the document formats actually used, contain fictitious data only and are not intended for submission to authorities or inspection bodies."}</p></div><div className="example-grid">{examples.map((example) => <article key={example.slug}><a className="example-preview" href={`/beispiele/${example.slug}.pdf?v=${exampleAssetVersion}`} target="_blank" rel="noreferrer"><Image src={`/beispiele/${example.slug}-vorschau.png?v=${exampleAssetVersion}`} alt={`${de ? example.de : example.en} – ${de ? "fiktives Muster" : "fictitious example"}`} width={example.width} height={example.height}/><span>{de ? "MUSTER · NICHT ZUR VORLAGE" : "SAMPLE · NOT FOR SUBMISSION"}</span></a><div><small>PDF · {de ? "MUSTER" : "SAMPLE"}</small><h3>{de ? example.de : example.en}</h3><p>{de ? example.textDe : example.textEn}</p><a href={`/beispiele/${example.slug}.pdf?v=${exampleAssetVersion}`} target="_blank" rel="noreferrer">{de ? "Muster-PDF ansehen" : "View sample PDF"}<Icon name="arrow"/></a></div></article>)}</div></section>

      <section className="order-section" id="auftrag"><div className="order-copy"><span className="kicker light">05 / {de ? "Auftrag" : "Order"}</span><h2>{de ? "Ein Produkt. 24,99 €." : "One product. €24.99."}</h2><p>{de ? "Keine Paketwahl und keine versteckten Aufpreise: drei fahrzeugbezogene Dokumente als digitales Paket mit europaweiter Datenblatt-Akzeptanzgarantie." : "No package selection and no hidden surcharges: three vehicle-specific documents in one digital package with our Europe-wide data-sheet acceptance guarantee."}</p><div className="price-card featured"><small>{de ? "Digitales Fahrzeugdatenpaket" : "Digital vehicle data package"}</small><strong>{PRODUCTS.data.price}</strong><span>{de ? "einmaliger Endpreis · inkl. MwSt." : "one-off total · VAT included"}</span><ul><li><Icon name="check"/> {de ? "COC-/Typgenehmigungsdatenblatt" : "COC/type-approval data sheet"}</li><li><Icon name="check"/> {de ? "Technisches Datenblatt" : "Technical data sheet"}</li><li><Icon name="check"/> {de ? "FIN-Bestätigung" : "VIN confirmation"}</li><li><Icon name="shield"/> {de ? "Europaweite Datenblatt-Akzeptanzgarantie" : "Europe-wide data-sheet acceptance guarantee"}</li></ul></div></div><OrderForm locale={locale} /></section>

      <section className="section knowledge" id="wissen"><div className="section-heading"><span className="kicker">06 / {de ? "Wissen" : "Knowledge"}</span><h2>{de ? "Zulassung besser vorbereitet angehen." : "Prepare for registration with confidence."}</h2></div><div className="knowledge-grid"><Link href={`/${locale}/wissen/auslaendisches-fahrzeug-in-deutschland-zulassen`}><small>8 MIN</small><h3>{de ? "Ausländisches Fahrzeug in Deutschland zulassen" : "Register a foreign vehicle in Germany"}</h3><span>{de ? "Checkliste lesen" : "Read the checklist"}<Icon name="arrow"/></span></Link><Link href={`/${locale}/wissen/deutsches-fahrzeug-im-eu-ausland-zulassen`}><small>7 MIN</small><h3>{de ? "Deutsches Fahrzeug im EU-Ausland zulassen" : "Register a German vehicle elsewhere in the EU"}</h3><span>{de ? "Ablauf verstehen" : "Understand the process"}<Icon name="arrow"/></span></Link><Link href={`/${locale}/wissen/coc-papiere`}><small>5 MIN</small><h3>{de ? "COC-Papiere: Original, Ersatz und Typdaten" : "COC papers: originals, replacement and type data"}</h3><span>{de ? "Unterschiede verstehen" : "Understand the differences"}<Icon name="arrow"/></span></Link><Link href={`/${locale}/wissen/technisches-datenblatt-importfahrzeug`}><small>6 MIN</small><h3>{de ? "Technisches Datenblatt für Importfahrzeuge" : "Technical data sheets for imported vehicles"}</h3><span>{de ? "Grundlagen lesen" : "Read the guide"}<Icon name="arrow"/></span></Link><Link href={`/${locale}/wissen/fin-fahrgestellnummer`}><small>4 MIN</small><h3>{de ? "FIN richtig finden und fotografieren" : "How to find and photograph a VIN"}</h3><span>{de ? "Fehler vermeiden" : "Avoid mistakes"}<Icon name="arrow"/></span></Link></div></section>

      <section className="section faq"><div className="section-heading"><span className="kicker">07 / FAQ</span><h2>{de ? "Kurz und eindeutig beantwortet." : "Clear answers, without detours."}</h2></div><div className="faq-list">{faq.map(([question, answer]) => <details key={question}><summary>{question}<span>+</span></summary><p>{answer}</p></details>)}</div></section>
    </main>
    <SiteFooter locale={locale}/>
  </>;
}
